language: minimal

dist: focal

services:
- docker

script:
- make test

deploy:
- provider: script
  script: make release
  on:
    repo: aler9/rtsp-simple-server
    tags: true

- provider: releases
  api_key: $GITHUB_API_KEY
  skip_cleanup: true
  file_glob: true
  file: release/*
  on:
    repo: aler9/rtsp-simple-server
    tags: true

- provider: script
  script: docker login -u aler9 -p $DOCKER_PASSWORD && make dockerhub
  on:
    repo: aler9/rtsp-simple-server
    tags: true
