blank_issues_enabled: false

contact_links:
  - name: Feature Request
    url: https://github.com/aler9/rtsp-simple-server/discussions/new
    about: Share ideas for new features

  - name: Question
    url: https://github.com/aler9/rtsp-simple-server/discussions/new
    about: Ask the community for help
