name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: make test

    - run: bash <(curl -s https://codecov.io/bash)

  test32:
    name: test32

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: make test32
