name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: "1.15"

    - run: sudo apt-get install -y --no-install-recommends ffmpeg

    - run: make test-nodocker

    - run: bash <(curl -s https://codecov.io/bash)
