name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - run: make test

    - run: bash <(curl -s https://codecov.io/bash)

  test32:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - run: make test32

  test_highlevel:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v2
      with:
        go-version: "1.19"

    - run: make test-highlevel-nodocker
